<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.0.1</Version>
    <Authors>Yiğit Kalaycıoğlu</Authors>
    <Product>N-Tier Mimari Oluşturucu</Product>
    <Copyright>© 2026 Yiğit Kalaycıoğlu</Copyright>
    <RepositoryUrl>https://github.com/yigitkalaycioglu/ntier-generator</RepositoryUrl>
  </PropertyGroup>

</Project>
